# Base de donnees distante - Acces a distance
# Hote: 212.227.91.82 | Port: 3306 | Base: salahmestaoui_db1
db.url=jdbc:mysql://212.227.91.82:3306/salahmestaoui_db1?useSSL=false&serverTimezone=Europe/Paris&allowPublicKeyRetrieval=true
db.username=salahmestaoui_db1
db.password=Salahmesmes123@
